name: watttime
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - appnope=0.1.4=pyhd8ed1ab_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=openblas
  - bottleneck=1.4.2=py39hbda83bc_0
  - brotli=1.0.9=h80987f9_8
  - brotli-bin=1.0.9=h80987f9_8
  - brotli-python=1.0.9=py39h313beb8_8
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2024.11.26=hca03da5_0
  - certifi=2024.8.30=py39hca03da5_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.2.0=py39h48ca7d4_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.6.7=py39h313beb8_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - exceptiongroup=1.2.0=py39hca03da5_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.3=h313beb8_0
  - fonttools=4.51.0=py39h80987f9_0
  - freetype=2.12.1=h1192e45_0
  - idna=3.7=py39hca03da5_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib_resources=6.4.0=py39hca03da5_0
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=8.15.0=py39hca03da5_0
  - jedi=0.19.1=py39hca03da5_0
  - jpeg=9e=h80987f9_3
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - kiwisolver=1.4.4=py39h313beb8_0
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - libbrotlicommon=1.0.9=h80987f9_8
  - libbrotlidec=1.0.9=h80987f9_8
  - libbrotlienc=1.0.9=h80987f9_8
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.17=h80987f9_1
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libiconv=1.16=h80987f9_3
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.39=h80987f9_0
  - libsodium=1.0.18=h27ca646_1
  - libtiff=4.5.1=h313beb8_0
  - libwebp-base=1.3.2=h80987f9_1
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_1
  - matplotlib=3.9.2=py39hca03da5_1
  - matplotlib-base=3.9.2=py39h7ef442a_1
  - matplotlib-inline=0.1.6=py39hca03da5_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - numexpr=2.10.1=py39h5d9532f_0
  - numpy=1.26.4=py39h3b2db8e_0
  - numpy-base=1.26.4=py39ha9811e2_0
  - openjpeg=2.5.2=h54b8e55_0
  - openssl=1.1.1w=h1a28f6b_0
  - packaging=24.1=py39hca03da5_0
  - pandas=2.2.3=py39hcf29cfe_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=11.0.0=py39hfaf4e14_0
  - pip=24.2=py39hca03da5_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - prompt-toolkit=3.0.43=py39hca03da5_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py39h1a28f6b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pygments=2.15.1=py39hca03da5_1
  - pyparsing=3.2.0=py39hca03da5_0
  - pysocks=1.7.1=py39hca03da5_0
  - python=3.9.6=hc70090a_5
  - python-dateutil=2.9.0post0=py39hca03da5_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2024.1=py39hca03da5_0
  - pyzmq=25.1.2=py39h313beb8_0
  - readline=8.2=h1a28f6b_0
  - requests=2.32.3=py39hca03da5_1
  - seaborn=0.13.2=py39hca03da5_0
  - setuptools=75.1.0=py39hca03da5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h80987f9_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tk=8.6.14=h6ba3021_0
  - tornado=6.4.1=py39h80987f9_0
  - tqdm=4.66.5=py39h33ce5c2_0
  - traitlets=5.14.3=py39hca03da5_0
  - typing_extensions=4.11.0=py39hca03da5_0
  - tzdata=2024b=h04d1e81_0
  - unicodedata2=15.1.0=py39h80987f9_0
  - urllib3=2.2.3=py39hca03da5_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.44.0=py39hca03da5_0
  - xz=5.4.6=h80987f9_1
  - zeromq=4.3.5=h313beb8_0
  - zipp=3.21.0=py39hca03da5_0
  - zlib=1.2.13=h18a0788_1
  - zstd=1.5.6=hfb09047_0
prefix: /Users/jen/miniconda3/envs/watttime
